---
- name: Pull docker image of OrganDonation
  hosts: all
  
  tasks:
    - name: Create docker network
      docker_network:
        name: NETWORK
        ipam_options:
          subnet: '192.168.3.0/24'
      
    - name: Create database container
      docker_container:
        name: mysql-con1
        image: mysql:8.0.23
        env:
          MYSQL_ROOT_PASSWORD: '@2B2c2d2'
          MYSQL_DATABASE: OrganDonation
          MYSQL_USER: 'chandanteja'
          MYSQL_PASSWORD: '@2B2c2d2'
        networks:
          - name: NETWORK
            ipv4_address: "192.168.3.22"
      
    - name: Create back-end container
      docker_container: 
        name: springboot-con1
        image: chandan321/organdonation-spring
        ports:
          - "9098:9098"
        networks:
          - name: NETWORK
      
    - name: Create front-end container
      docker_container:
        name: angular-con1
        image: chandan321/organdonation-angular
        ports:
          - "80:80"

